my $rh_preferences = {
	site_title => 'Sample Website By WPM',
	owner_name => 'John Sample',
	owner_email => 'john@sample.net',
	return_email => 'john@sample.net',
	smtp_host => 'localhost',
	wpm_module => 'CGI::WPM::MultiPage',
	wpm_subdir => 'content',
	wpm_prefs => 'content_prefs.pl',
	usg_subdir => 'usage',
	usg_dg_sub => 'usage_debug',
	log_usage => 1,
	debug_param => 'debugging',
	debug_value => 'on',
};
